FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/BrightnessController/BrightnessController.csproj", "BrightnessController/"]
RUN dotnet restore "BrightnessController/BrightnessController.csproj"
COPY ./src .
WORKDIR "/src/BrightnessController"
RUN dotnet build "BrightnessController.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BrightnessController.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BrightnessController.dll"]